[serve.static]
env = "BUN_PUBLIC_*"

[serve]

[build]
environment = "production"
minify = true
target = "node"
include = ["src/**/*","bin/**/*","scripts/**/*","dev-build/**/*","dist/**/*","enhanced-code-editor/**/*"]
root = "./"
require = ["src/index.ts","bun-env.d.ts","bin/codelab.js","scripts/generate-html.js","scripts/serve.ts","src/dev-server.tsx","src/dev-build/**/*"]
sourceMap = true

[install]
pkgs = ["react", "react-dom", "react-scripts"]
node = "22"
mirror = "https://registry.npmjs.org/"
node_modules = "node_modules"

[lint]
enabled = true
